version: '3'

services:
  database:
    image: 'mysql:latest'
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "rootpwd"
      MYSQL_USER: 'testuser'
      MYSQL_PASSWORD: 'testpassword'
    ports:
      - "3306:3306"

volumes:
  mysql:
